# trainDataFile: 'featurized_lm_segments.csv'
# trainDataFile: 'trainset_featurized_withfilter.csv'
trainDataFile: 'trainset_10000_featurized.csv'
# trainDataFile: 'trainset_10000_featurized_withextras.csv'
# goldDataFile: 'testset_featurized.csv'
# goldDataFile: 'testset_featurized_withextras.csv'
# goldDataFile: 'evalset_featurized_withextras.csv'
<<<<<<< HEAD
goldDataFile: 'testset_featurized.csv'
=======
goldDataFile: 'testset_featurized_withextras.csv'
>>>>>>> 54c2ac6b265afaaf9ff6dea0c8c3e7882b9880c6
labelCorrectionMap:
  'OTHER': 'SINUS'
  # 'NOISE': 'SINUS'
features:
   - 'b2b_var'
   - 'b2b_iqr'
   - 'b2b_range'
   - 'b2b_std'
   - 'sd1'
   - 'sd2'
   - 'sd1/sd2'
   - 'fft_1'
   - 'fft_2'
   - 'bpm'
   - 'pnn20'
   - 'rmssd'
   - 'pnn50'
   - 'ibi'
   - 'sdnn'
   - 'sdsd'
    #- 'b2b_var'
    # - 'b2b_iqr'
    # - 'b2b_range'
    # - 'b2b_std'
    # - 'sd1'
    # - 'sd2'
    # - 'sd1/sd2'
    # - 'fft_1'
    # - 'fft_2'
    # - 'bpm'
    # - 'pnn20'
    # - 'rmssd'
    # - 'pnn50'
    # - 'ibi'
    # - 'sdnn'
    # - 'sdsd'
