rawDataFile: ''
# trainDataFile: 'featurized_lm_segments.csv'
trainDataFile: 'trainset_featurized_lm.csv'
goldDataFile: 'testset_featurized.csv'
labelCorrectionMap:
  'OTHER': 'SINUS'
features:
  - 'b2b_var'
  - 'b2b_iqr'
  - 'b2b_range'
  - 'b2b_std'
  # - 'fft_1'
  # - 'fft_2'
  - 'beat_iqr'
  - 'bpm'
  - 'pnn20'
  - 'rmssd'
  - 'pnn50'
  - 'ibi'
  - 'sdnn'
  - 'sdsd'