# trainDataFile: 'featurized_lm_segments.csv'
# trainDataFile: 'trainset_featurized_withfilter.csv'
# trainDataFile: 'trainset_10000_featurized.csv'
trainDataFile: 'trainset_featurized.csv'
# trainDataFile: 'trainset_10000_featurized_withextras.csv'
# goldDataFile: 'testset_featurized.csv'
# goldDataFile: 'testset_featurized_withextras.csv'
# goldDataFile: 'evalset_featurized_withextras.csv'
# goldDataFile: 'testset_featurized.csv'
goldDataFile: 'evalset_featurized.csv'
labelCorrectionMap:
  'OTHER': 'NOT_AFIB'
  'SINUS': 'NOT_AFIB'
  # 'NOISE': 'SINUS'
features:
   - 'b2b_var'
   - 'b2b_iqr'
   - 'b2b_range'
   - 'b2b_std'
   - 'sd1'
   - 'sd2'
   - 'sd1/sd2'
   - 'bpm'
   - 'pnn20'
   - 'rmssd'
   - 'pnn50'
   - 'ibi'
   - 'sdnn'
   - 'sdsd'
   - 'HRV_LF'
   - 'HRV_HF'
   - 'HRV_LFHF'
   - 'sample_entropy'
   - 'hfd'
   - 'hopkins_statistic'
   - 'max_sil_score'
   - 'sse_1_clusters'
   - 'sse_2_clusters'
  #  - 'fft_1'
  #  - 'fft_2'
    #- 'b2b_var'
    # - 'b2b_iqr'
    # - 'b2b_range'
    # - 'b2b_std'
    # - 'sd1'
    # - 'sd2'
    # - 'sd1/sd2'
    # - 'fft_1'
    # - 'fft_2'
    # - 'bpm'
    # - 'pnn20'
    # - 'rmssd'
    # - 'pnn50'
    # - 'ibi'
    # - 'sdnn'
    # - 'sdsd'
