trainDataFile: 'trainset_featurized_nk.csv'
goldDataFile: 'final_annotations_featurized_nk.csv'
labelCorrectionMap:
  'OTHER': 'NOT_AFIB'
  'SINUS': 'NOT_AFIB'
  # 'NOISE': 'SINUS'
features_nk:
   - 'b2b_var'
   - 'b2b_iqr'
   - 'b2b_range'
   - 'b2b_std'
   - 'ecg_rate_mean'
   - 'hrv_rmssd'
   - 'hrv_sdnn'
   - 'hrv_sdsd'
   - 'hrv_sd1'
   - 'hrv_sd2'
   - 'hrv_sd1sd2'
   - 'hrv_pnn20'
   - 'hrv_pnn50'
   - 'hrv_lf'
   - 'hrv_hf'
   - 'hrv_lfhf'
   - 'hrv_sampen'
   - 'hrv_shanen'
   - 'hrv_apen'
   - 'hrv_hfd'
   - 'hopkins_statistic'
   - 'max_sil_score'
   - 'sse_1_clusters'
   - 'sse_2_clusters'
   - 'sse_diff'
features_trunc:
   - 'b2b_var'
   - 'b2b_iqr'
   - 'b2b_range'
   - 'b2b_std'
   - 'ecg_rate_mean'
   - 'hrv_rmssd'
   - 'hrv_sdnn'
   - 'hrv_sdsd'
features:
   - 'b2b_var'
   - 'b2b_iqr'
   - 'b2b_range'
   - 'b2b_std'
   - 'sd1'
   - 'sd2'
   - 'sd1/sd2'
   - 'bpm'
   - 'pnn20'
   - 'rmssd'
   - 'pnn50'
   - 'ibi'
   - 'sdnn'
   - 'sdsd'
   - 'HRV_LF'
   - 'HRV_HF'
   - 'HRV_LFHF'
   - 'sample_entropy'
   - 'hfd'
   - 'hopkins_statistic'
   - 'max_sil_score'
   - 'sse_1_clusters'
   - 'sse_2_clusters'
  #  - 'fft_1'
  #  - 'fft_2'
    #- 'b2b_var'
    # - 'b2b_iqr'
    # - 'b2b_range'
    # - 'b2b_std'
    # - 'sd1'
    # - 'sd2'
    # - 'sd1/sd2'
    # - 'fft_1'
    # - 'fft_2'
    # - 'bpm'
    # - 'pnn20'
    # - 'rmssd'
    # - 'pnn50'
    # - 'ibi'
    # - 'sdnn'
    # - 'sdsd'
